# This is a basic workflow to help you get started with Actions

name: Run script session2.sh when session2.zip change

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-and-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      - name: hash current file .zip
        run: |
          run: echo "hash_current=$(md5sum <(unzip -p session2.zip) | awk '{print $1}')" >> $GITHUB_ENV

      # kiểm tra và giải nén sesssion2.zip nếu tồn tại   
      - name: hash previous file zip
        run: |
          # Kiểm tra và giải nén phiên bản trước của session2.zip (nếu tồn tại)
          if git show HEAD^:session2.zip > session2_previous.zip 2>/dev/null; then
            echo "hash_previous=$(md5sum <(unzip -p session2_previous.zip) | awk '{print $1}')" >> $GITHUB_ENV
            rm -rf  session2_previous.zip
          fi
     
       
      # kiểm tra kết quả nếu đúng thì chạy lại script và push kết quả lên github
      - name: Run session2.sh if session2.zip content changed
        if: env.hash_current != env.hash_previous 
        run: |
          # run script session2.sh if content session2.zip change
          bash session2.sh
          
          # push the result to GitHub after updating session2.zip 
          git add .
          git commit -m "Updated results after session2.zip changes"
          git push -u origin main
        
